server:
  port: 8000
  servlet:
    context-path: /LEDGER




#MyBatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.ledger.entity
  global-config:
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: AUTO
      field-strategy: default
      db-type: mysql
    banner: false #关闭MyBatis-Plus自带的打印Banner
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

ledger:
  shiro:
    cacheManager: ehcacheManager