spring:
#  cloud:
#    config:
#      #开发环境本地优先级最高
#      allow-override: true
#      override-none: true
#      override-system-properties: true
  #配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.128.52.48:3306/LEDGER?serverTimeZone=GMT+8&characterEncoding=utf8&useSSL=false&rewriteBatchedStatements=true&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: ledger
    password: '123456'
    druid:
      validationQuery: SELECT 1
      # 初始化配置
      initialSize: 10
      # 最小连接数
      minIdle: 3
      # 最大连接数
      maxActive: 15
      # 最大空闲时间
      minEvictableIdleTimeMillis: 180000
      testOnBorrow: false
      testWhileIdle: true
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: true
      poolPreparedStatements: true
      maxOpenPreparedStatements: 100


logging:
  file:
    path: F:\\logs

# 文件存储路径
file:
  path: F:\ledger\file\
  avatar: F:\ledger\avatar\
  # 文件大小 /M
  maxSize: 100
  avatarMaxSize: 5
